# Generated by Django 6.1.1 on 2026-09-19 03:17

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_claps_post_claps_count_clap'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.profile_avatar_upload_path, validators=[blog.models.validate_avatar_size]),
        ),
    ]
